language: c

compiler:
  - gcc
  - clang

os:
  - linux
  - osx

env:
  - ARCH=x86_64
  - ARCH=i386

before_install:
  - gpg --recv-keys 3CEA9B8868BC3852618EB5B4707F91A424F006F5
  - wget http://www.intra2net.com/en/developer/libftdi/download/libftdi1-1.2.tar.bz2
  - wget http://www.intra2net.com/en/developer/libftdi/download/libftdi1-1.2.tar.bz2.sig
  - gpg --trust-model always --verify libftdi1-1.2.tar.bz2.sig
  - tar -xjf libftdi1-1.2.tar.bz2

install:
  - cd libftdi1-1.2
  - if [ "$TRAVIS_OS_NAME" = "linux" ];
    then
      sudo apt-get update -qq;
      if [ "$ARCH" = "x86_64" ];
      then
        sudo apt-get install -qq libusb-1.0-0-dev;
      elif [ "$ARCH" = "i386" ];
      then
        sudo apt-get install -qq gcc-multilib libusb-1.0-0-dev:i386;
      fi
    fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ];
    then
      brew update;
      brew install libusb;
    fi
  - mkdir build
  - cd build
  - if [ "$ARCH" = "x86_64" ];
    then
      cmake ../;
    elif [ "$ARCH" = "i386" ];
    then
      cmake -DCMAKE_C_FLAGS="-m32" -DCMAKE_SHARED_LINKER_FLAGS="-m32" ../;
    fi
  - make
  - sudo make install
  - cd ../../

script:
  - if [ "$ARCH" = "i386" ];
    then
      export CFLAGS="-m32";
      make;
    fi

before_deploy:
  - tar -czf ftdi_unbricker-$TRAVIS_TAG-$TRAVIS_OS_NAME-$ARCH.tar.gz ./COPYING.txt ./README.md ./brick ./unbrick

deploy:
  provider: releases
  api_key:
    secure: iQv119YN4v85B8hgeZLIDPqEGnQPrfq7326XKMPTmgLCPhv92jPs38ArAAygtoZahZiDEqgtiW/l6HKyS/Y1vEG9afqbMCun+4Cy35gAKBi5FFvORcPjINXuS1cxUJ4gHam73Br8hEQ1jV0Nv6rk03XrBtTpjEH6fpu+v4EHcuA=
  file: "ftdi_unbricker-$TRAVIS_TAG-$TRAVIS_OS_NAME-$ARCH.tar.gz"
  on:
    repo: cyrozap/ftdi-unbricker
    tags: true
    all_branches: true
    condition: "$CC = gcc"
